server:
  port: 8017

spring:
  datasource:
    url: jdbc:postgresql://subscription-db-svc:5432/subscription_db
    username: admin
    password: sub123
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: exception

  kafka:
    bootstrap-servers: kafka-broker-svc:9092

    consumer:
      group-id: subscription-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

    admin:
      auto-create: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        use-default-response-messages: false


