server:
  port: 8017

spring:
  datasource:
    url: jdbc:postgresql://subscription-db-svc:5432/subscription_db
    username: admin
    password: sub123
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.tablePrefix: QRTZ_

  messages:
    basename: exception

  kafka:
    bootstrap-servers: kafka-broker-svc:9092
    producer:
      retries: 3

  threads:
    virtual:
      enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
        use-default-response-messages: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

resilience4j:
  circuitbreaker:
    instances:
      kafkaOutboxBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5

